project:
  type: book

book:
  title: "Learning Hub Manual"
  
  author-meta: "Halina Do-Linh & Camila Vargas Pouslen"
  date-meta: "10/28/2022"
  
  page-footer: 
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    
    - part: nceas-programs.qmd
      chapters: 
        - adc-background.qmd
        - lter-background.qmd
        - neon-background.qmd
        - delta-science-background.qmd
        - openscapes-background.qmd
        - reprod-research-techniques-background.qmd
        - snapp-background.qmd
        - meds-background.qmd
        - morpho-background.qmd
        - noaa-restore-background.qmd
        - nasa-noaa-background.qmd
        
    - other-eds-opps.qmd



    - conferences.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual



