# Environmental Data Science Opportunities {.unnumbered}

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(reactable) # create tables
library(googlesheets4) # read in google sheets
```

Ongoing list of Environmental Data Science (EDS) opportunities outside of NCEAS. To add to this list

## EDS Programs

EDS programs that provide EDS or related curriculum.

```{r, echo=FALSE, message=FALSE}
# read in googlesheet "masters-program"
eds_opps <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1y5_7cpGG1eb56cnMZl9sb-AbfaSCc3hidZjs5L7VZoA/edit?usp=sharing", sheet = "eds-opps")
```

```{r, echo=FALSE}
# create table using reactable
reactable::reactable(eds_opps,
                     defaultPageSize = 5,
                     highlight = TRUE,
                     striped = TRUE,
                     filterable = TRUE,
                     columns = list(
                       type = colDef("Type",
                                     filterInput = function(values, name) {
                                       htmltools::tags$select(
                                         # Set to undefined to clear the filter
                                         onchange = sprintf("Reactable.setFilter('type-select',
                                                            '%s', event.target.value ||
                                                            undefined)", name),
                                         # "All" has an empty value to clear the filter, and is the default option
                                         htmltools::tags$option(value = "", "All"),
                                         lapply(unique(sort(values)), htmltools::tags$option),
                                         "aria-label" = sprintf("Filter %s", name),
                                         style = "width: 100%; height: 28px;"
                                       ) # EO tags$select
                                     }
                                     ), # EO colDef type
                       name = colDef("Name",
                                     minWidth = 110,
                                     filterInput = function(values, name) {
                                       htmltools::tags$select(
                                         # Set to undefined to clear the filter
                                         onchange = sprintf("Reactable.setFilter('name-select',
                                                            '%s', event.target.value ||
                                                            undefined)", name),
                                         # "All" has an empty value to clear the filter, and is the default option
                                         htmltools::tags$option(value = "", "All"),
                                         lapply(unique(sort(values)), htmltools::tags$option),
                                         "aria-label" = sprintf("Filter %s", name),
                                         style = "width: 100%; height: 28px;"
                                       ) # EO tags$select
                                     }
                                     ),
                       affiliation = colDef("Affiliation",
                                            minWidth = 110),
                       twitter_handle = colDef("Twitter Handle",
                                               minWidth = 110,
                                               # add link
                                               cell = function(twitter_handle, index) {
                                                 url <- eds_opps[[index, "twitter_link"]]
                                                 htmltools::tags$a(href = url, 
                                                                   target = "_blank",
                                                                   as.character(twitter_handle))
                                               } 
                                               ),
                       twitter_link = colDef(show = FALSE),
                       offering = colDef("Offering",
                                         # add link
                                         cell = function(offering, index) {
                                           url <- eds_opps[[index, "offering_link"]]
                                           htmltools::tags$a(href = url,
                                                             target = "_blank",
                                                             as.character(offering))
                                         }
                                         ),
                       offering_link = colDef(show = FALSE),
                       brief_description = colDef("Description", 
                                                  minWidth = 200)
                     ), # EO columns
                     elementId = c("type-select","name-select"),
                     defaultSorted = "name"
                     ) # EO reactable


```
